### ISSUE TITLE
Discover ServiceGUID or UUID

### ISSUE THREAD

**Issue by noblevarghese** [PolarGoose/BluetoothDevicePairing#4]
### This is not an Issue instead an addition request

Can you try to add/discover the UUID or SDP of the Bluetooth device? Reference: https://www.bluetooth.com/specifications/assigned-numbers/service-discovery/ & https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-bluetooth#servicesallowedlist-usage-guide

**Comment by PolarGoose** [comment]
@noblevarghese,

Hm... good question. I had an idea of adding this functionality in the past, but I gave up because it is very difficult and inconsistent. If you are interested, you can look at this [stackoverflow answer](https://stackoverflow.com/a/62108753/7585517).
Another problem is that my Utility uses [Windows.Devices.Enumeration API](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Enumeration?redirectedfrom=MSDN&view=winrt-19041) which doesn't provide this functionality.

Therefore, sorry, this feature is out of the scope of this tool.

As an alternative, you can use [btdiscovery](https://bluetoothinstaller.com/bluetooth-command-line-tools/btdiscovery.html) shareware console utility which has this feature (`-s` flag)
